# Generated by Django 2.0.6 on 2018-07-28 11:31

from django.db import migrations, models
import django.db.models.deletion
import intranet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0009_drop_unneeded_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntranetDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(unique=True, upload_to='intranet')),
                ('published', models.BooleanField(default=True)),
                ('authorization', models.SmallIntegerField(choices=[(3, 'admin'), (0, 'aucun'), (1, 'étudiant'), (2, 'prof')], default=0, verbose_name='autorisation')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cms.Module')),
            ],
            options={
                'verbose_name': 'Intranet',
                'verbose_name_plural': 'Intranet',
            },
        ),
    ]
