# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='doc/')),
                ('titre', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=False)),
            ],
        ),

        migrations.RemoveField(
            model_name='document',
            name='docfile',
        ),
    ]
