# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domaine',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'ordering': ('nom',)},
        ),
        migrations.AlterModelOptions(
            name='processus',
            options={'ordering': ('code',)},
        ),
        migrations.AddField(
            model_name='competence',
            name='tyoe',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
    ]
