# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170419_1333'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='UploadDoc',
        ),
    ]
