# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20161224_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competence',
            old_name='tyoe',
            new_name='type',
        ),
    ]
