# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-03 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20170419_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploaddoc',
            options={'verbose_name': 'UploadDoc'},
        ),
        migrations.AddField(
            model_name='module',
            name='didactique_published',
            field=models.BooleanField(default=False),
        ),
    ]
