# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20161224_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='didactique',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='module',
            name='pratique_prof',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='processus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.Processus'),
        ),
        migrations.AlterField(
            model_name='module',
            name='evaluation',
            field=models.TextField(default=''),
        ),
    ]
