# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20161224_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('code',)},
        ),
        migrations.AlterField(
            model_name='module',
            name='nom',
            field=models.CharField(default='Nom du module', max_length=100),
        ),
    ]
