# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20161224_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='libelle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='souscompetence',
            name='libelle',
            field=models.CharField(max_length=250),
        ),
    ]
