# Generated by Django 2.0.6 on 2018-09-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_drop_unneeded_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(default='Code', max_length=10, unique=True),
        ),
    ]
