# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(),
        ),
    ]
