# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20170104_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='processus',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
