# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_processus_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objectif',
            name='type',
        ),
        migrations.AddField(
            model_name='ressource',
            name='type',
            field=models.CharField(choices=[('Savoir', 'savoir'), ('Savoir méthodologique', 'savoir méthodologique'), ('Savoir relationnel', 'savoir relationnel')], default='Savoir', max_length=30),
        ),
    ]
