# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_auto_20170127_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objectif',
            old_name='libelle',
            new_name='nom',
        ),
    ]
