# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_auto_20170129_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
    ]
