# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_remove_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='periode_presentiel',
            field=models.IntegerField(verbose_name='Période en présentiel'),
        ),
        migrations.AlterField(
            model_name='module',
            name='pratique_prof',
            field=models.IntegerField(default=0, verbose_name='Pratique professionnelle'),
        ),
        migrations.AlterField(
            model_name='module',
            name='travail_perso',
            field=models.IntegerField(verbose_name='Travail personnel'),
        ),
    ]
