# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_remove_module_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='module',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Module'),
        ),
    ]
