# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-08 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_competence_processus_eval'),
        ('cms', '0017_auto_20170308_0437'),
    ]

    operations = [
    ]
