# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_merge_20170308_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='processus_eval',
        ),
        migrations.RemoveField(
            model_name='document',
            name='module',
        ),
        migrations.AddField(
            model_name='competence',
            name='proces_eval',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.Processus'),
        ),
    ]
