# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_auto_20170406_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
