# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-06 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20170406_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='texte',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
